# Generated by Django 5.2.5 on 2025-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名ユーザーa8f56207', max_length=30, unique=True),
        ),
    ]
