# Generated by Django 5.2.5 on 2025-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名6ff21f9db524', max_length=30, unique=True),
        ),
    ]
