# Generated by Django 5.2.5 on 2025-08-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名8ec0a92df709', max_length=30, unique=True),
        ),
    ]
