# Generated by Django 5.2.5 on 2025-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with the quiz.', related_name='quizzes', to='quizzes.tag', verbose_name='Tags'),
        ),
    ]
