# Generated by Django 5.2.5 on 2025-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.JSONField(default={'q': 0}, error_messages={'blank': 'This field cannot be blank.'}, help_text='The correct answer(s) for the quiz question.', verbose_name='Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='Indicates whether the quiz has been checked.', verbose_name='Is Checked'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, help_text='The question content in plain text.', max_length=500, verbose_name='Question'),
        ),
    ]
