# Generated by Django 5.2.5 on 2025-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_answer_quiz_is_checked_alter_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(error_messages={'blank': 'This field cannot be blank.'}, help_text='The question content in plain text.', max_length=500, verbose_name='Question'),
        ),
    ]
