# Generated by Django 5.2.5 on 2025-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(error_messages={'blank': 'This field cannot be blank.'}, help_text='The question content in plain text. 500 characters or fewer.', max_length=500, verbose_name='Question'),
        ),
    ]
