# Generated by Django 5.2.5 on 2025-08-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.JSONField(error_messages={'blank': 'This field cannot be blank.'}, help_text='The correct answer(s) for the quiz question. 1000 characters or fewer.', max_length=1000, verbose_name='Answer'),
        ),
    ]
