# Generated by Django 5.2.5 on 2025-08-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.JSONField(error_messages={'blank': 'This field cannot be blank.'}, help_text='The correct answer(s) for the quiz question.', verbose_name='Answer'),
        ),
    ]
