### Registration
POST http://localhost:8000/api/auth/registration/
Content-Type: application/json

{
    "username": "shino2",
    "email": "shino2@example.com",
    "password": "ThisIsA#StrongPass1",
    "password2": "ThisIsA#StrongPass1"
}

### login
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "shino2",
    "password": "ThisIsA#StrongPass2"
}

### detail
GET http://localhost:8000/api/auth/detail
Content-Type: application/json
Authorization: Token be60a6e4b952131bdd3546b8aed38da92ecb8bcb

### update
PUT http://localhost:8000/api/auth/update/
Content-Type: application/json
Authorization: Token be60a6e4b952131bdd3546b8aed38da92ecb8bcb

{
    "username": "shino2",
    "email": "shino2@example.com",
    "nickname": "testnick2"
}

### password change
PUT http://localhost:8000/api/auth/password_change/
Content-Type: application/json
Authorization: Token be60a6e4b952131bdd3546b8aed38da92ecb8bcb

{
    "old_password": "ThisIsA#StrongPass2",
    "new_password": "ThisIsA#StrongPass3",
    "new_password2": "ThisIsA#StrongPass3"
}

### logout
POST http://localhost:8000/api/auth/logout/
Content-Type: application/json
Authorization: Token be60a6e4b952131bdd3546b8aed38da92ecb8bcb

