# Generated by Django 5.2.5 on 2025-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名630c8b3983af', max_length=30, unique=True),
        ),
    ]
