# Generated by Django 5.2.5 on 2025-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名fb34fe319020', max_length=30, unique=True),
        ),
    ]
