# Generated by Django 5.2.5 on 2025-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名0ecabb3cee01', max_length=30, unique=True),
        ),
    ]
